components:
  schemas:
    Item:
      properties:
        id:
          type: string
        content:
          type: string
        timestamp:
          type: integer
        user:
          type: string
        dlp_incident_id:
          type: integer
      type: object
    GetNotesResponse:
      properties:
        data:
          items:
            $ref: "#/components/schemas/Item"
          type: array
        status:
          example: success
          type: string
      type: object
    AddNoteRequest:
      properties:
        content:
          type: string
        user:
          type: string
      required:
        - content
      type: object
    ValidationResponse:
      properties:
        data:
          properties:
            message:
              description: user facing error message
              type: string
          type: object
        status:
          example: success | error
          type: string
      type: object
info:
  description: DLP Incident Notes API
  title: DLP Incident Notes API
  version: 1.0.0
openapi: 3.0.3
paths:
  /incidents/dlpincidents/{id}/notes:
    get:
      parameters:
        - description: ID of the DLP Incident
          in: path
          name: id
          required: true
          schema:
            type: string
          x-example: "1234345435346"
      responses:
        "200":
          description: OK
          content:
            application/json:
              examples:
                Response Example:
                  value:
                    data:
                      - id: "123"
                        content: "this is text"
                        timestamp: 1720777406
                        dlp_incident_id: 12345
                        user: "psingh@netskope.com"
                      - id: "234"
                        content: "this is text"
                        user: "psingh-test@netskope.com"
                        timestamp: 1720777408
                        dlp_incident_id: 12345
                    status: success
              schema:
                $ref: "#/components/schemas/GetNotesResponse"
        "400":
          description: Invalid path parameters
          content:
            application/json:
              examples:
                Missing Input Params:
                  value:
                    data:
                      message: "Missing parameters"
                    status: error
                Incident not found:
                  value:
                    data:
                      message: "Incident not found"
                    status: error
              schema:
                $ref: "#/components/schemas/ValidationResponse"
        "500":
          description: Server Error
          content:
            application/json:
              examples:
                Internal Error:
                  value:
                    data:
                      message: "Internal Error"
                    status: error
              schema:
                $ref: "#/components/schemas/ValidationResponse"
      summary: Returns the list of notes for a given incident
    post:
      parameters:
        - description: ID of the DLP Incident
          in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AddNoteRequest"
            example:
              content: "this is text"
              user: "psingh-test@netskope.com"
      responses:
        "201":
          description: OK
          content:
            application/json:
              example:
                id: "123"
                content: "this is text"
                timestamp: "123"
                user: "psingh@netskope.com"
              schema:
                $ref: "#/components/schemas/Item"
        "400":
          description: Invalid path parameters
          content:
            application/json:
              examples:
                Missing Input Params:
                  value:
                    data:
                      message: "Missing parameters"
                    status: error
                Incident not found:
                  value:
                    data:
                      message: "Incident not found"
                    status: error
              schema:
                $ref: "#/components/schemas/ValidationResponse"
        "409":
          description: Cannot add more notes
          content:
            application/json:
              examples:
                Note limit exceeded:
                  value:
                    data:
                      message: "Max limit of 25 notes reached for the given Incident ID"
                    status: error
              schema:
                $ref: "#/components/schemas/ValidationResponse"
        "500":
          description: Server Error
          content:
            application/json:
              examples:
                Internal Error:
                  value:
                    data:
                      message: "Internal Error"
                    status: error
              schema:
                $ref: "#/components/schemas/ValidationResponse"
      summary: Adds new note for a given incident
    x-netskope-params:
      apiGroup: ims_notes
      customerFacing: false
      serviceConfig: ims-restapisvc
      version: 2
