components:
  schemas:
    Scim:
      properties:
        client_name:
          type: string
        creation_time:
          type: string
        last_used_time:
          nullable: true
          type: string
        scim_id:
          type: integer
        token:
          type: string
      type: object
    limit:
      maximum: 100
      minimum: 1
      type: integer
    offset:
      default: 0
      minimum: 0
      type: integer
    sortorder:
      enum:
        - desc
        - asc
      type: string
info:
  contact:
    name: ""
  description: MS Settings
  title: ms-settings
  version: 1.0.0
openapi: 3.0.3
paths:
  /ui/settings/onpremise/addonurls:
    get:
      description: Retrieve Scim Table data.
      parameters:
        - in: query
          name: version
          schema:
            default: 1
            description: Property for version
            enum:
              - 1
            type: integer
      responses:
        "200":
          content:
            application/json:
              schema:
                example:
                  data:
                    adConnectorUrl: https:downloader-host/dlr/XXXXXXXXXXXXXX
                    addOnManagerUrl: https:addon-host/adsync/XXXXXXXXXXXXXX
                  msg: Scim account created successfully
                  success: true
                properties:
                  data:
                    properties:
                      adConnectorUrl:
                        type: string
                      addOnManagerUrl:
                        type: string
                    type: object
                  msg:
                    type: string
                  success:
                    type: boolean
                type: object
          description: Successful response
        5XX:
          description: Unexpected error.
      summary: Retrieve Scim Table data.
    x-netskope-params:
      apiGroup: ms-settings
      customerFacing: true
      nsBeta: true
      serviceConfig: ms-settings
      version: 2
  /ui/settings/onpremise/addonurls/v1:
    get:
      description: Retrieve Scim Table data.
      responses:
        "200":
          content:
            application/json:
              schema:
                example:
                  data:
                    adConnectorUrl: https:downloader-host/dlr/XXXXXXXXXXXXXX
                    addOnManagerUrl: https:addon-host/adsync/XXXXXXXXXXXXXX
                  msg: Scim account created successfully
                  success: true
                properties:
                  data:
                    properties:
                      adConnectorUrl:
                        type: string
                      addOnManagerUrl:
                        type: string
                    type: object
                  msg:
                    type: string
                  success:
                    type: boolean
                type: object
          description: Successful response
        5XX:
          description: Unexpected error.
      summary: Retrieve Scim Table data.
    x-netskope-params:
      apiGroup: ms-settings
      customerFacing: true
      nsBeta: true
      serviceConfig: ms-settings
      version: 2
  /ui/settings/scim:
    delete:
      description: Deletes scim account.
      parameters:
        - in: query
          name: version
          schema:
            default: 1
            description: Version number
            enum:
              - 1
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              example:
                name: Test 101
              properties:
                name:
                  type: string
              required:
                - name
              type: object
        description: Json scim data
      responses:
        "200":
          content:
            application/json:
              schema:
                example:
                  msg: Scim account deleted successfully
                  success: true
                properties:
                  msg:
                    type: string
                  success:
                    type: boolean
                type: object
          description: Successful response
        4XX:
          content:
            application/json:
              schema:
                example:
                  msg: Validation error ...
                  success: false
                properties:
                  msg:
                    type: string
                  success:
                    type: boolean
                type: object
          description: Client error
        5XX:
          description: Unexpected error.
      summary: Deletes scim account.
    get:
      description: Retrieve Scim Table data.
      parameters:
        - in: query
          name: version
          schema:
            default: 1
            description: Version number
            enum:
              - 1
            type: integer
        - in: query
          name: limit
          schema:
            $ref: "#/components/schemas/limit"
        - in: query
          name: offset
          schema:
            $ref: "#/components/schemas/offset"
        - in: query
          name: sortby
          schema:
            default: client_name
            description: Property to order
            enum:
              - client_name
              - token
              - creation_time
              - last_time_used
            type: string
        - in: query
          name: sortorder
          schema:
            $ref: "#/components/schemas/sortorder"
      responses:
        "200":
          content:
            application/json:
              schema:
                example:
                  data:
                    count: 2
                    result:
                      - client_name: test 1
                        creation_time: "2022-04-05T11:48:11.000Z"
                        last_used_time: null
                        scim_id: 1
                        token: XASODASJASOKOJSDSAADSOKO
                      - client_name: test 2
                        creation_time: "2022-04-05T11:48:11.000Z"
                        last_used_time: null
                        scim_id: 2
                        token: XASODASJASOKOJSDSAADSOKO
                  msg: ""
                  success: true
                properties:
                  data:
                    properties:
                      count:
                        type: integer
                      result:
                        items:
                          $ref: "#/components/schemas/Scim"
                        type: array
                    type: object
                  msg:
                    type: string
                  success:
                    type: boolean
                type: object
          description: Successful response
        4XX:
          content:
            application/json:
              schema:
                example:
                  msg: Validation error ...
                  success: false
                properties:
                  msg:
                    type: string
                  success:
                    type: boolean
                type: object
          description: Client error
        5XX:
          description: Unexpected error.
      summary: Retrieve Scim Table data.
    post:
      description: Inserts scim account.
      parameters:
        - in: query
          name: version
          schema:
            default: 1
            description: Version number
            enum:
              - 1
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              example:
                name: Test 101
              properties:
                name:
                  type: string
              required:
                - name
              type: object
        description: Json scim data
      responses:
        "200":
          content:
            application/json:
              schema:
                example:
                  msg: Scim account created successfully
                  success: true
                properties:
                  msg:
                    type: string
                  success:
                    type: boolean
                type: object
          description: Successful response
        4XX:
          content:
            application/json:
              schema:
                example:
                  msg: Validation error ...
                  success: false
                properties:
                  msg:
                    type: string
                  success:
                    type: boolean
                type: object
          description: Client error
        5XX:
          description: Unexpected error.
      summary: Inserts scim account.
    x-netskope-params:
      apiGroup: ms-settings
      customerFacing: true
      nsBeta: true
      serviceConfig: ms-settings
      version: 2
  /ui/settings/scim/url:
    get:
      description: Retrieve Scim Table data.
      parameters:
        - in: query
          name: version
          schema:
            default: 1
            description: Version number
            enum:
              - 1
            type: integer
      responses:
        "200":
          content:
            application/json:
              schema:
                example:
                  data: https://addon-host/SCIM/V2/
                  msg: null
                  success: true
                properties:
                  data:
                    type: string
                  msg:
                    type: string
                  success:
                    type: boolean
                type: object
          description: Successful response
        5XX:
          description: Unexpected error.
      summary: Retrieve Scim Table data.
    x-netskope-params:
      apiGroup: ms-settings
      customerFacing: true
      nsBeta: true
      serviceConfig: ms-settings
      version: 2
  /ui/settings/scim/url/v1:
    get:
      description: Retrieve Scim Table data.
      responses:
        "200":
          content:
            application/json:
              schema:
                example:
                  data: https://addon-host/SCIM/V2/
                  msg: null
                  success: true
                properties:
                  data:
                    type: string
                  msg:
                    type: string
                  success:
                    type: boolean
                type: object
          description: Successful response
        5XX:
          description: Unexpected error.
      summary: Retrieve Scim Table data.
    x-netskope-params:
      apiGroup: ms-settings
      customerFacing: true
      nsBeta: true
      serviceConfig: ms-settings
      version: 2
  /ui/settings/scim/v1:
    delete:
      description: Deletes scim account.
      requestBody:
        content:
          application/json:
            schema:
              example:
                name: Test 101
              properties:
                name:
                  type: string
              required:
                - name
              type: object
        description: Json scim data
      responses:
        "200":
          content:
            application/json:
              schema:
                example:
                  msg: Scim account deleted successfully
                  success: true
                properties:
                  msg:
                    type: string
                  success:
                    type: boolean
                type: object
          description: Successful response
        4XX:
          content:
            application/json:
              schema:
                example:
                  msg: Validation error ...
                  success: false
                properties:
                  msg:
                    type: string
                  success:
                    type: boolean
                type: object
          description: Client error
        5XX:
          description: Unexpected error.
      summary: Deletes scim account.
    get:
      description: Retrieve Scim Table data.
      parameters:
        - in: query
          name: limit
          schema:
            $ref: "#/components/schemas/limit"
        - in: query
          name: offset
          schema:
            $ref: "#/components/schemas/offset"
        - in: query
          name: sortby
          schema:
            default: client_name
            description: Property to order
            enum:
              - client_name
              - token
              - creation_time
              - last_time_used
            type: string
        - in: query
          name: sortorder
          schema:
            $ref: "#/components/schemas/sortorder"
      responses:
        "200":
          content:
            application/json:
              schema:
                example:
                  data:
                    count: 2
                    result:
                      - client_name: test 1
                        creation_time: "2022-04-05T11:48:11.000Z"
                        last_used_time: null
                        scim_id: 1
                        token: XASODASJASOKOJSDSAADSOKO
                      - client_name: test 2
                        creation_time: "2022-04-05T11:48:11.000Z"
                        last_used_time: null
                        scim_id: 2
                        token: XASODASJASOKOJSDSAADSOKO
                  msg: ""
                  success: true
                properties:
                  data:
                    properties:
                      count:
                        type: integer
                      result:
                        items:
                          $ref: "#/components/schemas/Scim"
                        type: array
                    type: object
                  msg:
                    type: string
                  success:
                    type: boolean
                type: object
          description: Successful response
        4XX:
          content:
            application/json:
              schema:
                example:
                  msg: Validation error ...
                  success: false
                properties:
                  msg:
                    type: string
                  success:
                    type: boolean
                type: object
          description: Client error
        5XX:
          description: Unexpected error.
      summary: Retrieve Scim Table data.
    post:
      description: Inserts scim account.
      requestBody:
        content:
          application/json:
            schema:
              example:
                name: Test 101
              properties:
                name:
                  type: string
              required:
                - name
              type: object
        description: Json scim data
      responses:
        "200":
          content:
            application/json:
              schema:
                example:
                  msg: Scim account created successfully
                  success: true
                properties:
                  msg:
                    type: string
                  success:
                    type: boolean
                type: object
          description: Successful response
        4XX:
          content:
            application/json:
              schema:
                example:
                  msg: Validation error ...
                  success: false
                properties:
                  msg:
                    type: string
                  success:
                    type: boolean
                type: object
          description: Client error
        5XX:
          description: Unexpected error.
      summary: Inserts scim account.
    x-netskope-params:
      apiGroup: ms-settings
      customerFacing: true
      nsBeta: true
      serviceConfig: ms-settings
      version: 2
servers:
  - description: Development server
    url: http://localhost:3000/api/v2/ui
tags: []
